# Generated by Django 5.2.8 on 2025-11-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('parents', 'Parents Only'), ('teachers', 'Teachers Only'), ('staff', 'Staff Only'), ('specific_class', 'Specific Class')], default='all', max_length=20, verbose_name='Target Audience')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/', verbose_name='Attachment')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish Date')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.school', verbose_name='School')),
                ('target_classes', models.ManyToManyField(blank=True, help_text='Select classes if target audience is "Specific Class"', related_name='announcements', to='accounts.class', verbose_name='Target Classes')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['school', 'is_published'], name='announcemen_school__1c5fc8_idx'), models.Index(fields=['target_audience'], name='announcemen_target__e32955_idx'), models.Index(fields=['-created_at'], name='announcemen_created_f85040_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_starred', models.BooleanField(default=False, verbose_name='Is Starred')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('is_deleted_by_sender', models.BooleanField(default=False, verbose_name='Deleted by Sender')),
                ('is_deleted_by_recipient', models.BooleanField(default=False, verbose_name='Deleted by Recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communications.message', verbose_name='Reply To')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'is_deleted_by_sender'], name='messages_sender__0c40a1_idx'), models.Index(fields=['recipient', 'is_deleted_by_recipient', 'is_read'], name='messages_recipie_5d04f6_idx'), models.Index(fields=['-created_at'], name='messages_created_17cff9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('announcement', 'Announcement'), ('message', 'New Message'), ('attendance', 'Attendance Alert'), ('fee', 'Fee Reminder'), ('exam', 'Exam Notification'), ('result', 'Result Published'), ('timetable', 'Timetable Update'), ('system', 'System Notification')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx')],
            },
        ),
    ]
