# Generated by Django 5.2.8 on 2025-11-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('brother', 'Brother'), ('sister', 'Sister'), ('guardian', 'Legal Guardian'), ('other', 'Other')], max_length=20, verbose_name='Relation')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Annual Income')),
                ('alternate_phone', models.CharField(blank=True, max_length=17, verbose_name='Alternate Phone')),
                ('office_phone', models.CharField(blank=True, max_length=17, verbose_name='Office Phone')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='National ID/SSN')),
                ('is_primary_contact', models.BooleanField(default=True, verbose_name='Is Primary Contact')),
                ('can_pickup_student', models.BooleanField(default=True, verbose_name='Can Pick Up Student')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='accounts.school', verbose_name='School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'db_table': 'guardians',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True, verbose_name='Admission Number')),
                ('roll_number', models.CharField(blank=True, max_length=50, verbose_name='Roll Number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Blood Group')),
                ('religion', models.CharField(blank=True, max_length=50, verbose_name='Religion')),
                ('nationality', models.CharField(default='United States', max_length=50, verbose_name='Nationality')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('previous_school', models.CharField(blank=True, max_length=200, verbose_name='Previous School')),
                ('date_of_admission', models.DateField(verbose_name='Date of Admission')),
                ('date_of_leaving', models.DateField(blank=True, null=True, verbose_name='Date of Leaving')),
                ('uses_transport', models.BooleanField(default=False, verbose_name='Uses School Transport')),
                ('transport_route', models.CharField(blank=True, max_length=100, verbose_name='Transport Route')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('class_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.class', verbose_name='Class')),
                ('guardians', models.ManyToManyField(blank=True, related_name='wards', to='students.guardian', verbose_name='Guardians')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.school', verbose_name='School')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.section', verbose_name='Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('substitute', 'Substitute')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('date_of_leaving', models.DateField(blank=True, null=True, verbose_name='Date of Leaving')),
                ('highest_qualification', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('diploma', 'Diploma'), ('certification', 'Certification')], default='bachelor', max_length=20, verbose_name='Highest Qualification')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Specialization')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
                ('languages_known', models.CharField(blank=True, max_length=200, verbose_name='Languages Known')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Relation')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teachers/resumes/', verbose_name='Resume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='accounts.school', verbose_name='School')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='accounts.subject', verbose_name='Subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['employee_id'],
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['school'], name='guardians_school__e86940_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_assigned', 'section'], name='students_school__2907a9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='students_admissi_664d58_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='students_school__58564c_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'is_active'], name='teachers_school__fc0673_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['employee_id'], name='teachers_employe_e16945_idx'),
        ),
    ]
