# Generated by Django 5.2.8 on 2025-11-10 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_school__2907a9_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'class_assigned'], name='students_school__58efe0_idx'),
        ),
    ]
