# Generated by Django 5.2.8 on 2025-11-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('excused', 'Excused Absence')], default='present', max_length=20, verbose_name='Status')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Marked By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-date', 'student'],
                'indexes': [models.Index(fields=['student', 'date'], name='attendance_student_0943ef_idx'), models.Index(fields=['date', 'status'], name='attendance_date_32df9b_idx'), models.Index(fields=['student', 'status'], name='attendance_student_bc7a65_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
