# Generated by Django 5.2.8 on 2025-11-10 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Exam Name')),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('mid_term', 'Mid Term'), ('final', 'Final Exam'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('annual', 'Annual'), ('entrance', 'Entrance Exam'), ('placement', 'Placement Test')], max_length=20, verbose_name='Exam Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('result_declaration_date', models.DateField(blank=True, null=True, verbose_name='Result Declaration Date')),
                ('is_result_published', models.BooleanField(default=False, verbose_name='Is Result Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.academicyear', verbose_name='Academic Year')),
                ('classes', models.ManyToManyField(related_name='exams', to='accounts.class', verbose_name='Classes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='accounts.school', verbose_name='School')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marks Obtained')),
                ('max_marks', models.PositiveIntegerField(default=100, verbose_name='Maximum Marks')),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+ (Outstanding)'), ('A', 'A (Excellent)'), ('B+', 'B+ (Very Good)'), ('B', 'B (Good)'), ('C+', 'C+ (Above Average)'), ('C', 'C (Average)'), ('D', 'D (Below Average)'), ('F', 'F (Fail)')], max_length=2, verbose_name='Grade')),
                ('theory_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Theory Marks')),
                ('practical_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Practical Marks')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Is Passed')),
                ('is_absent', models.BooleanField(default=False, verbose_name='Is Absent')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('teacher_comments', models.TextField(blank=True, verbose_name='Teacher Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL, verbose_name='Entered By')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam', verbose_name='Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='accounts.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'db_table': 'exam_results',
                'ordering': ['-exam__start_date', 'student', 'subject'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'academic_year'], name='exams_school__64376b_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_date', 'end_date'], name='exams_start_d_819ce9_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='exam_end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'student'], name='exam_result_exam_id_007d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'subject'], name='exam_result_student_39e2a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.CheckConstraint(condition=models.Q(('marks_obtained__lte', models.F('max_marks'))), name='marks_lte_max_marks'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student', 'subject')},
        ),
    ]
